# -*- coding: utf-8 -*-
"""The analytical core- Python

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19GyAd9LZpmmiWjNkRD1LTB27_rUGiLqN

## **Week 2 - The analytical core (Python)**
"""

# Upload the SQL view file

from google.colab import files
uploaded = files.upload()

import pandas as pd
import numpy as np

print("Libraries loaded successfully.")

#Load data

def load_data(filepath):
    """
    Load customer-level RFM base data exported from SQL view.
    """
    print("Loading data...")
    df = pd.read_csv(filepath)
    print(f"Data loaded. Total records: {len(df)}")
    return df


# Replace with your actual file name
df = load_data("customer_rfm_base.csv")

df.head()

#Calculate RFM scores

def calculate_rfm_scores(df):
    """
    Convert Recency, Frequency, Monetary into 1–5 quantile scores.
    """

    print("Calculating RFM scores...")

    # Recency → Lower is better
    df['R_Score'] = pd.qcut(df['Recency'], 5, labels=[5,4,3,2,1])

    # Frequency → Higher is better
    df['F_Score'] = pd.qcut(
        df['Frequency'].rank(method='first'),
        5,
        labels=[1,2,3,4,5]
    )

    # Monetary → Higher is better
    df['M_Score'] = pd.qcut(
        df['MonetaryValue'],
        5,
        labels=[1,2,3,4,5]
    )

    # Convert to integers
    df[['R_Score','F_Score','M_Score']] = \
        df[['R_Score','F_Score','M_Score']].astype(int)

    print("RFM scoring complete.")
    return df


df = calculate_rfm_scores(df)

df.head()

#Segmenting the customers based on scoring

def segment_customers(df):
    """
    Assign segment labels based on RFM scoring logic.
    """

    print("Segmenting customers...")

    def segment_logic(row):

        if row['R_Score'] >= 4 and row['F_Score'] >= 4 and row['M_Score'] >= 4:
            return 'Champions'

        elif row['F_Score'] >= 4:
            return 'Loyalists'

        elif row['R_Score'] <= 2:
            return 'Hibernating'

        else:
            return 'Potential'

    df['Segment'] = df.apply(segment_logic, axis=1)

    print("Segmentation complete.")
    return df


df = segment_customers(df)

df['Segment'].value_counts()

#Validate champions that have highest average spend

def validate_segments(df):
    """
    Validate that Champions demonstrate highest average spend.
    """

    print("Validating segment performance...")

    validation = (
        df.groupby('Segment')['MonetaryValue']
        .mean()
        .sort_values(ascending=False)
    )

    print("\nAverage Monetary Value by Segment:")
    print(validation)

    return validation


validation = validate_segments(df)

#Export segmented results

output_filename = "rfm_segmented_output.csv"

df.to_csv(output_filename, index=False)

from google.colab import files
files.download(output_filename)

print("Segmented output exported successfully.")